### ISSUE TITLE
Source file missing from repo?

### ISSUE THREAD

**Issue by EduardGabriel** [UCREL/FreeTxt-Flask#1]
Hello!

I'm currently doing my Bcs final yr CS project at Cardiff U on improving the functionalities of this platform!
Currently running into some issues in running this locally. 
Firstly, not sure which Python version was used, could this be clarified?
Installing the requirements seemed to be mostly fine on py 3.11, however, across a variety of Py versions (3.8, .11, .12 & others), there seems to be an issue with the installation of the canvas requirement, and seeing version discrepancies and conflicts.

ERROR: Ignored the following versions that require a different python version: 0.1.0 Requires-Python >=2.7, <3.0; 0.1.4 Requires-Python >=3.12,<4.0
ERROR: Could not find a version that satisfies the requirement canvas (from versions: none)
ERROR: No matching distribution found for canvas

Finally, after removing the canvas from requirements temporarily,  and trying to run the app, an error occurs as a file appears to be missing from the repo. 

\website\__init__.py", line 42, in create_app
    from .Text_analysis import TextAnalysis
ModuleNotFoundError: No module named 'website.Text_analysis'

It appears that that file was omitted ? The subsequent file File_Analysis is present 

Thank you very much for your time, and I look forward to further collaborating on this project!
Eduard G Isai

**Comment by Nouran-Khallaf** [comment]
resolved
