### ISSUE TITLE
Missing source file

### ISSUE THREAD

**Issue by IzaKozinska** [UCREL/FreeTxt-Flask#2]
Hello,

I am doing my BCs final year project by implementing new sentiment analysis functionalities to this application.

When attempting to locally run this locally I have come up with an issue. The error I receive is as follows:

"\FreeTxt-Flask-main\website\__init__.py", line 42, in create_app
from .Text_analysis import TextAnalysis
ModuleNotFoundError: No module named 'website.Text_analysis'

It appears that a file named Text_analysis is missing. Is there an error with the repo or is it an error on my behalf?

Thank you for your time and I look forward to hearing back from you,
Izabela Kozinska

**Comment by Nouran-Khallaf** [comment]
resolved
